name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to the latest version
        with:
          python-version: 3.11  # Adjust this as per your project's Python version

      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: Set up Virtual Environment and Install Dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt || true  # Ignore error if requirements.txt is missing

      - name: Run Tests and Generate Coverage Report
        run: |
          source env/bin/activate
          pip install coverage  # Ensure coverage is installed
          coverage run manage.py test
          coverage xml

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1  # Updated to the latest stable version
        env:
          SONAR_HOST_URL: http://localhost:9000  # Adjust this if using a hosted version
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Food_Online  # Match this with sonar.projectKey in sonar-project.properties
